image:
  name: docker/compose:1.24.0
  entrypoint: ["/bin/sh", "-c"]

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

services:
- docker:dind

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker-compose down
    - docker-compose -f docker-compose.yml -f docker-compose.registry.yml build --pull
    - docker-compose -f docker-compose.yml -f docker-compose.registry.yml push
