version: '3.7'

services:

  traefik:
    command: --docker.swarmMode
    deploy:
      placement:
        constraints:
        - node.role == manager


  front:
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '1'
      labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:scoreboard.sthack.fr
      - traefik.port=3000
      - traefik.protocol=http,wss,ws,https
      - traefik.backend.loadbalancer.stickiness=true
      - traefik.docker.network=sthack_traefiknet
