version: '3.7'

services:
  traefik:
    image: sthack-traefik
    build:
      context: ./reverseproxy
      dockerfile: Dockerfile
    ports:
    - 80:80
    - 443:443
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
    restart: always
    networks:
    - traefiknet
    depends_on:
    - front

  front:
    image: sthack-interface-neo
    build:
      context: ./front
      dockerfile: Dockerfile
    command: npm start
    restart: always
    environment:
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - DB_CONNECTION_STRING=mongodb://sthackadmin:gxwv3mcntd7rjyrv64ho07vetw0k1lli@mongo:27017/admin
    - ADMIN_NAME=admin_sthack
    - CLOSED_TASK_DELAY=0
    - SESSION_SECRET=0d0807c26595bf67a0437e9f2d49eb3e
    - SESSION_KEY=sthackSession
    - ADMIN_PATH=/la_page_admin_secret_sthack_pouet
    - TITLE=Sthack
    - BASE_SCORE=50
    networks:
    - main
    - traefiknet
    depends_on:
    - redis
    - mongo
    volumes:
    - tasks_img:/app/public/img/tasks

  redis:
    image: redis:alpine
    networks:
    - main

  mongo:
    image: mongo
    restart: always
    environment:
    - MONGO_INITDB_ROOT_USERNAME=sthackadmin
    - MONGO_INITDB_ROOT_PASSWORD=gxwv3mcntd7rjyrv64ho07vetw0k1lli
    networks:
    - main
    volumes:
    - mongo_data:/data/db

networks:
  main:
  traefiknet:

volumes:
  mongo_data:
  tasks_img:
