version: '3.7'

services:
  front:
    environment:
      NODE_ENV: production
#     volumes :
#     - ./front/src:/app/src

#   mongo:
#     volumes:
#     - mongo_data:/data/db

# volumes:
#   mongo_data:
#   shared_images:
