version: '3.7'

services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
      target: build
    environment:
      NODE_ENV: development
    ports:
    - 9229:9229
    command: node --inspect=0.0.0.0:9229 --inspect-brk /src/src/server.js
    restart: "no"
    volumes :
    - ./front/src:/src/src
