version: '3.7'

services:
  traefik:
    command: --api # Enables the web UI and tells Traefik to listen to docker
    ports:
    - 8080:8080 # The Web UI (enabled by --api)

  front:
    command: >
        sh -c "
        npm install
        && npm run build
        && npm run docker-dev"
    environment:
    - NODE_ENV=development
    ports:
    - 9229:9229
    volumes :
    - ./front:/app
    - node_modules:/app/node_modules
    # - ./logs:/root/.npm/_logs
    labels:
    - traefik.enable=true
    - traefik.frontend.rule=Host:localhost
    - traefik.port=3000
    - traefik.protocol=http
    - traefik.backend.loadbalancer.stickiness=true
    - traefik.docker.network=sthack-interface-neo_traefiknet

volumes:
  node_modules:
