version: '3.7'

services:

  traefik:
    command: --docker.swarmMode
    labels:
    - traefik.docker.domain=localhost
    deploy:
      placement:
        constraints:
        - node.role == manager


  front:
    labels:
    - traefik.enable=true
    - traefik.frontend.rule=Host:localhost
    - traefik.port=3000
    - traefik.protocol=http
    - traefik.backend.loadbalancer.stickiness=true
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '1'
